name = "SimplePIC"
uuid = "0491d90b-bdae-4f99-86d9-be190dd34edd"
authors = ["Stepan Roucka <stepan@roucka.eu> and contributors"]
version = "0.1.0-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MonteCarloCollisions = "3af9cca3-6439-492f-bb75-d94037938865"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Accessors = ">= 0.1.0"
Distributions = ">= 0.20"
FFTW = ">= 1"
LinearAlgebra = ">= 1"
MonteCarloCollisions = "0.1.0"
Plots = ">= 1"
Random = ">= 1"
SparseArrays = ">= 1"
StaticArrays = ">= 1"
StatsBase = ">= 0.20"
julia = ">= 1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
