[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimplePIC = "0491d90b-bdae-4f99-86d9-be190dd34edd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
